# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.11.0
    hooks:
    -   id: gitleaks
        alias: gitleaks-once
        stages: [manual]
        pass_filenames: false
        args: [--no-git, -p, .]
-   repo: https://github.com/zricethezav/gitleaks
    rev:  v8.11.0
    hooks:
    -   id: gitleaks
