name: Comncurrency

on:
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "${{ github.run_number }}"

      - name: Run a multi-line script
        run: |
          rand=$(( ( RANDOM % 10 )  + 1 ))
          sec=$(date +%S)
          sleep $(($rand + $sec))
          echo Add other actions to build,
          echo test, and deploy your project.


  build2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "${{ github.run_number }}"

      - name: Run a multi-line script
        run: |
          rand=$(( ( RANDOM % 10 )  + 1 ))
          sec=$(date +%S)
          sleep $(($rand + $sec))
          echo Add other actions to build,
          echo test, and deploy your project.

  build3:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "${{ github.run_number }}"

      - name: Run a multi-line script
        run: |
          rand=$(( ( RANDOM % 10 )  + 1 ))
          sec=$(date +%S)
          sleep $(($rand + $sec))
          echo Add other actions to build,
          echo test, and deploy your project.
