name: Comncurrency

on:
  workflow_dispatch:

concurrency: staging_environment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: sleep 5m

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
