name: Comncurrency

on:
  issues:
    types: [opened]

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: sleep 1m

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
